package z.nova.rifmobolgame.model.round.multi

import z.nova.rifmobolgame.R
import z.nova.rifmobolgame.model.round.LevelData

class RoundInfoImplMulti(private val id: Int = 0): RoundRepoMulti {

        override fun getRoundInfMulti(): RoundInfoMulti {

            val resultTextRoundMUlit = when(id){
                1 -> LevelData.listTextRoundMulti[0]
                2 -> LevelData.listTextRoundMulti[1]
                3 -> LevelData.listTextRoundMulti[2]
                4 -> LevelData.listTextRoundMulti[3]
                5 -> LevelData.listTextRoundMulti[4]
                6 -> LevelData.listTextRoundMulti[0]
                7-> LevelData.listTextRoundMulti[1]
                8 -> LevelData.listTextRoundMulti[2]
                9 -> LevelData.listTextRoundMulti[3]
                10 -> LevelData.listTextRoundMulti[4]
                11 -> LevelData.listTextRoundMulti[0]
                12 -> LevelData.listTextRoundMulti[1]
                13 -> LevelData.listTextRoundMulti[2]
                14 -> LevelData.listTextRoundMulti[3]
                15 -> LevelData.listTextRoundMulti[4]
                16 -> LevelData.listTextRoundMulti[0]
                17 -> LevelData.listTextRoundMulti[1]
                18 -> LevelData.listTextRoundMulti[2]
                19 -> LevelData.listTextRoundMulti[3]
                20 -> LevelData.listTextRoundMulti[4]
                21 -> LevelData.listTextRoundMulti[0]
                22 -> LevelData.listTextRoundMulti[1]
                23 -> LevelData.listTextRoundMulti[2]
                24 -> LevelData.listTextRoundMulti[3]
                25 -> LevelData.listTextRoundMulti[4]
                26 -> LevelData.listTextRoundMulti[0]
                27 -> LevelData.listTextRoundMulti[1]
                28 -> LevelData.listTextRoundMulti[2]
                29 -> LevelData.listTextRoundMulti[3]
                30 -> LevelData.listTextRoundMulti[4]
                31 -> LevelData.listTextRoundMulti[0]
                32 -> LevelData.listTextRoundMulti[1]
                33 -> LevelData.listTextRoundMulti[2]
                34 -> LevelData.listTextRoundMulti[3]
                35 -> LevelData.listTextRoundMulti[4]
                else -> R.string.eror
            }

            val resultBackgroundLvl = when(id){
                1 -> LevelData.listBackground[0]
                2 -> LevelData.listBackground[1]
                3 -> LevelData.listBackground[2]
                4 -> LevelData.listBackground[3]
                5 -> LevelData.listBackground[4]
                6 -> LevelData.listBackground[5]
                7 -> LevelData.listBackground[6]
                8 -> LevelData.listBackground[7]
                9 -> LevelData.listBackground[8]
                10 -> LevelData.listBackground[9]
                11 -> LevelData.listBackground[0]
                12 -> LevelData.listBackground[1]
                13 -> LevelData.listBackground[2]
                14 -> LevelData.listBackground[3]
                15 -> LevelData.listBackground[4]
                16 -> LevelData.listBackground[5]
                17 -> LevelData.listBackground[6]
                18 -> LevelData.listBackground[7]
                19 -> LevelData.listBackground[8]
                20 -> LevelData.listBackground[9]
                21 -> LevelData.listBackground[0]
                22 -> LevelData.listBackground[1]
                23 -> LevelData.listBackground[2]
                24 -> LevelData.listBackground[3]
                25 -> LevelData.listBackground[4]
                26 -> LevelData.listBackground[5]
                27 -> LevelData.listBackground[6]
                28 -> LevelData.listBackground[7]
                29 -> LevelData.listBackground[8]
                30 -> LevelData.listBackground[9]
                31 -> LevelData.listBackground[0]
                32 -> LevelData.listBackground[1]
                33 -> LevelData.listBackground[2]
                34 -> LevelData.listBackground[3]
                35 -> LevelData.listBackground[4]
                else -> LevelData.listBackground[0]
            }

            val resultcouplet = when(id){
                1 -> LevelData.listcouplet[0]
                2 -> LevelData.listcouplet[1]
                3 -> LevelData.listcouplet[2]
                4 -> LevelData.listcouplet[3]
                5 -> LevelData.listcouplet[4]
                6 -> LevelData.listcouplet[5]
                7 -> LevelData.listcouplet[6]
                8 -> LevelData.listcouplet[7]
                9 -> LevelData.listcouplet[8]
                10 -> LevelData.listcouplet[9]
                11 -> LevelData.listcouplet[10]
                12 -> LevelData.listcouplet[11]
                13 -> LevelData.listcouplet[12]
                14 -> LevelData.listcouplet[13]
                15 -> LevelData.listcouplet[14]
                16 -> LevelData.listcouplet[15]
                17 -> LevelData.listcouplet[16]
                18 -> LevelData.listcouplet[17]
                19 -> LevelData.listcouplet[18]
                20 -> LevelData.listcouplet[19]
                21 -> LevelData.listcouplet[20]
                22 -> LevelData.listcouplet[21]
                23 -> LevelData.listcouplet[22]
                24 -> LevelData.listcouplet[23]
                25 -> LevelData.listcouplet[24]
                26 -> LevelData.listcouplet[25]
                27 -> LevelData.listcouplet[26]
                28 -> LevelData.listcouplet[27]
                29 -> LevelData.listcouplet[28]
                30 -> LevelData.listcouplet[29]
                31 -> LevelData.listcouplet[30]
                32 -> LevelData.listcouplet[31]
                33 -> LevelData.listcouplet[32]
                34 -> LevelData.listcouplet[33]
                35 -> LevelData.listcouplet[34]
                else -> R.string.eror
            }

            val resultbtnone = when(id){
                1 -> LevelData.listbtnone[0]
                2 -> LevelData.listbtnone[1]
                3 -> LevelData.listbtnone[2]
                4 -> LevelData.listbtnone[3]
                5 -> LevelData.listbtnone[4]
                6 -> LevelData.listbtnone[5]
                7 -> LevelData.listbtnone[6]
                8 -> LevelData.listbtnone[7]
                9 -> LevelData.listbtnone[8]
                10 -> LevelData.listbtnone[9]
                11 -> LevelData.listbtnone[10]
                12 -> LevelData.listbtnone[11]
                13 -> LevelData.listbtnone[12]
                14 -> LevelData.listbtnone[13]
                15 -> LevelData.listbtnone[14]
                16 -> LevelData.listbtnone[15]
                17 -> LevelData.listbtnone[16]
                18 -> LevelData.listbtnone[17]
                19 -> LevelData.listbtnone[18]
                20 -> LevelData.listbtnone[19]
                21 -> LevelData.listbtnone[20]
                22 -> LevelData.listbtnone[21]
                23 -> LevelData.listbtnone[22]
                24 -> LevelData.listbtnone[23]
                25 -> LevelData.listbtnone[24]
                26 -> LevelData.listbtnone[25]
                27 -> LevelData.listbtnone[26]
                28 -> LevelData.listbtnone[27]
                29 -> LevelData.listbtnone[28]
                30 -> LevelData.listbtnone[29]
                31 -> LevelData.listbtnone[30]
                32 -> LevelData.listbtnone[31]
                33 -> LevelData.listbtnone[32]
                34 -> LevelData.listbtnone[33]
                35 -> LevelData.listbtnone[34]
                else -> R.string.eror
            }

            val resultbtntwo = when(id){
                1 -> LevelData.listbtntwo[0]
                2 -> LevelData.listbtntwo[1]
                3 -> LevelData.listbtntwo[2]
                4 -> LevelData.listbtntwo[3]
                5 -> LevelData.listbtntwo[4]
                6 -> LevelData.listbtntwo[5]
                7 -> LevelData.listbtntwo[6]
                8 -> LevelData.listbtntwo[7]
                9 -> LevelData.listbtntwo[8]
                10 -> LevelData.listbtntwo[9]
                11 -> LevelData.listbtntwo[10]
                12 -> LevelData.listbtntwo[11]
                13 -> LevelData.listbtntwo[12]
                14 -> LevelData.listbtntwo[13]
                15 -> LevelData.listbtntwo[14]
                16 -> LevelData.listbtntwo[15]
                17 -> LevelData.listbtntwo[16]
                18 -> LevelData.listbtntwo[17]
                19 -> LevelData.listbtntwo[18]
                20 -> LevelData.listbtntwo[19]
                21 -> LevelData.listbtntwo[20]
                22 -> LevelData.listbtntwo[21]
                23 -> LevelData.listbtntwo[22]
                24 -> LevelData.listbtntwo[23]
                25 -> LevelData.listbtntwo[24]
                26 -> LevelData.listbtntwo[25]
                27 -> LevelData.listbtntwo[26]
                28 -> LevelData.listbtntwo[27]
                29 -> LevelData.listbtntwo[28]
                30 -> LevelData.listbtntwo[29]
                31 -> LevelData.listbtntwo[30]
                32 -> LevelData.listbtntwo[31]
                33 -> LevelData.listbtntwo[32]
                34 -> LevelData.listbtntwo[33]
                35 -> LevelData.listbtntwo[34]
                else -> R.string.eror
            }

            val resultbtnthree = when(id){
                1 -> LevelData.listbtnthree[0]
                2 -> LevelData.listbtnthree[1]
                3 -> LevelData.listbtnthree[2]
                4 -> LevelData.listbtnthree[3]
                5 -> LevelData.listbtnthree[4]
                6 -> LevelData.listbtnthree[5]
                7 -> LevelData.listbtnthree[6]
                8 -> LevelData.listbtnthree[7]
                9 -> LevelData.listbtnthree[8]
                10 -> LevelData.listbtnthree[9]
                11 -> LevelData.listbtnthree[10]
                12 -> LevelData.listbtnthree[11]
                13 -> LevelData.listbtnthree[12]
                14 -> LevelData.listbtnthree[13]
                15 -> LevelData.listbtnthree[14]
                16 -> LevelData.listbtnthree[15]
                17 -> LevelData.listbtnthree[16]
                18 -> LevelData.listbtnthree[17]
                19 -> LevelData.listbtnthree[18]
                20 -> LevelData.listbtnthree[19]
                21 -> LevelData.listbtnthree[20]
                22 -> LevelData.listbtnthree[21]
                23 -> LevelData.listbtnthree[22]
                24 -> LevelData.listbtnthree[23]
                25 -> LevelData.listbtnthree[24]
                26 -> LevelData.listbtnthree[25]
                27 -> LevelData.listbtnthree[26]
                28 -> LevelData.listbtnthree[27]
                29 -> LevelData.listbtnthree[28]
                30 -> LevelData.listbtnthree[29]
                31 -> LevelData.listbtnthree[30]
                32 -> LevelData.listbtnthree[31]
                33 -> LevelData.listbtnthree[32]
                34 -> LevelData.listbtnthree[33]
                35 -> LevelData.listbtnthree[34]
                else -> R.string.eror
            }

            val resultbtnfour = when(id){
                1 -> LevelData.listbtnfour[0]
                2 -> LevelData.listbtnfour[1]
                3 -> LevelData.listbtnfour[2]
                4 -> LevelData.listbtnfour[3]
                5 -> LevelData.listbtnfour[4]
                6 -> LevelData.listbtnfour[5]
                7 -> LevelData.listbtnfour[6]
                8 -> LevelData.listbtnfour[7]
                9 -> LevelData.listbtnfour[8]
                10 -> LevelData.listbtnfour[9]
                11 -> LevelData.listbtnfour[10]
                12 -> LevelData.listbtnfour[11]
                13 -> LevelData.listbtnfour[12]
                14 -> LevelData.listbtnfour[13]
                15 -> LevelData.listbtnfour[14]
                16 -> LevelData.listbtnfour[15]
                17 -> LevelData.listbtnfour[16]
                18 -> LevelData.listbtnfour[17]
                19 -> LevelData.listbtnfour[18]
                20 -> LevelData.listbtnfour[19]
                21 -> LevelData.listbtnfour[20]
                22 -> LevelData.listbtnfour[21]
                23 -> LevelData.listbtnfour[22]
                24 -> LevelData.listbtnfour[23]
                25 -> LevelData.listbtnfour[24]
                26 -> LevelData.listbtnfour[25]
                27 -> LevelData.listbtnfour[26]
                28 -> LevelData.listbtnfour[27]
                29 -> LevelData.listbtnfour[28]
                30 -> LevelData.listbtnfour[29]
                31 -> LevelData.listbtnfour[30]
                32 -> LevelData.listbtnfour[31]
                33 -> LevelData.listbtnfour[32]
                34 -> LevelData.listbtnfour[33]
                35 -> LevelData.listbtnfour[34]
                else -> R.string.eror
            }

            val resulmusic1 = when(id){
                1 -> LevelData.listmusic1[0]
                2 -> LevelData.listmusic1[1]
                3 -> LevelData.listmusic1[2]
                4 -> LevelData.listmusic1[3]
                5 -> LevelData.listmusic1[4]
                6 -> LevelData.listmusic1[5]
                7 -> LevelData.listmusic1[6]
                8 -> LevelData.listmusic1[7]
                9 -> LevelData.listmusic1[8]
                10 -> LevelData.listmusic1[9]
                11 -> LevelData.listmusic1[10]
                12 -> LevelData.listmusic1[11]
                13 -> LevelData.listmusic1[12]
                14 -> LevelData.listmusic1[13]
                15 -> LevelData.listmusic1[14]
                16 -> LevelData.listmusic1[15]
                17 -> LevelData.listmusic1[16]
                18 -> LevelData.listmusic1[17]
                19 -> LevelData.listmusic1[18]
                20 -> LevelData.listmusic1[19]
                21 -> LevelData.listmusic1[20]
                22 -> LevelData.listmusic1[21]
                23 -> LevelData.listmusic1[22]
                24 -> LevelData.listmusic1[23]
                25 -> LevelData.listmusic1[24]
                26 -> LevelData.listmusic1[25]
                27 -> LevelData.listmusic1[26]
                28 -> LevelData.listmusic1[27]
                29 -> LevelData.listmusic1[28]
                30 -> LevelData.listmusic1[29]
                31 -> LevelData.listmusic1[30]
                32 -> LevelData.listmusic1[31]
                33 -> LevelData.listmusic1[32]
                34 -> LevelData.listmusic1[33]
                35 -> LevelData.listmusic1[34]
                else -> R.raw.eggs1
            }

            val resulmusic2 = when(id){
                1 -> LevelData.listmusic2[0]
                2 -> LevelData.listmusic2[1]
                3 -> LevelData.listmusic2[2]
                4 -> LevelData.listmusic2[3]
                5 -> LevelData.listmusic2[4]
                6 -> LevelData.listmusic2[5]
                7 -> LevelData.listmusic2[6]
                8 -> LevelData.listmusic2[7]
                9 -> LevelData.listmusic2[8]
                10 -> LevelData.listmusic2[9]
                11 -> LevelData.listmusic2[10]
                12 -> LevelData.listmusic2[11]
                13 -> LevelData.listmusic2[12]
                14 -> LevelData.listmusic2[13]
                15 -> LevelData.listmusic2[14]
                16 -> LevelData.listmusic2[15]
                17 -> LevelData.listmusic2[16]
                18 -> LevelData.listmusic2[17]
                19 -> LevelData.listmusic2[18]
                20 -> LevelData.listmusic2[19]
                21 -> LevelData.listmusic2[20]
                22 -> LevelData.listmusic2[21]
                23 -> LevelData.listmusic2[22]
                24 -> LevelData.listmusic2[23]
                25 -> LevelData.listmusic2[24]
                26 -> LevelData.listmusic2[25]
                27 -> LevelData.listmusic2[26]
                28 -> LevelData.listmusic2[27]
                29 -> LevelData.listmusic2[28]
                30 -> LevelData.listmusic2[29]
                31 -> LevelData.listmusic2[30]
                32 -> LevelData.listmusic2[31]
                33 -> LevelData.listmusic2[32]
                34 -> LevelData.listmusic2[33]
                35 -> LevelData.listmusic2[34]
                else -> R.raw.eggs2
            }

            val resultTextDialogLose = when(id){
                1 -> LevelData.listtextDialogLose[0]
                2 -> LevelData.listtextDialogLose[1]
                3 -> LevelData.listtextDialogLose[2]
                4 -> LevelData.listtextDialogLose[3]
                5 -> LevelData.listtextDialogLose[4]
                6 -> LevelData.listtextDialogLose[0]
                7 -> LevelData.listtextDialogLose[1]
                8 -> LevelData.listtextDialogLose[2]
                9 -> LevelData.listtextDialogLose[3]
                10 -> LevelData.listtextDialogLose[4]
                11 -> LevelData.listtextDialogLose[0]
                12 -> LevelData.listtextDialogLose[1]
                13 -> LevelData.listtextDialogLose[2]
                14 -> LevelData.listtextDialogLose[3]
                15 -> LevelData.listtextDialogLose[4]
                16 -> LevelData.listtextDialogLose[0]
                17 -> LevelData.listtextDialogLose[1]
                18 -> LevelData.listtextDialogLose[2]
                19 -> LevelData.listtextDialogLose[3]
                20 -> LevelData.listtextDialogLose[4]
                21 -> LevelData.listtextDialogLose[0]
                22 -> LevelData.listtextDialogLose[1]
                23 -> LevelData.listtextDialogLose[2]
                24 -> LevelData.listtextDialogLose[3]
                25 -> LevelData.listtextDialogLose[4]
                26 -> LevelData.listtextDialogLose[0]
                27 -> LevelData.listtextDialogLose[1]
                28 -> LevelData.listtextDialogLose[2]
                29 -> LevelData.listtextDialogLose[3]
                30 -> LevelData.listtextDialogLose[4]
                31 -> LevelData.listtextDialogLose[0]
                32 -> LevelData.listtextDialogLose[1]
                33 -> LevelData.listtextDialogLose[2]
                34 -> LevelData.listtextDialogLose[3]
                35 -> LevelData.listtextDialogLose[4]
                else -> R.string.eror
            }

            val resultTextDialogWin = when(id){
                1 -> LevelData.listtextDialogWin[0]
                2 -> LevelData.listtextDialogWin[1]
                3 -> LevelData.listtextDialogWin[2]
                4 -> LevelData.listtextDialogWin[3]
                5 -> LevelData.listtextDialogWin[4]
                6 -> LevelData.listtextDialogWin[0]
                7 -> LevelData.listtextDialogWin[1]
                8 -> LevelData.listtextDialogWin[2]
                9 -> LevelData.listtextDialogWin[3]
                10 -> LevelData.listtextDialogWin[4]
                11 -> LevelData.listtextDialogWin[0]
                12 -> LevelData.listtextDialogWin[1]
                13 -> LevelData.listtextDialogWin[2]
                14 -> LevelData.listtextDialogWin[3]
                15 -> LevelData.listtextDialogWin[4]
                16 -> LevelData.listtextDialogWin[0]
                17 -> LevelData.listtextDialogWin[1]
                18 -> LevelData.listtextDialogWin[2]
                19 -> LevelData.listtextDialogWin[3]
                20 -> LevelData.listtextDialogWin[4]
                21 -> LevelData.listtextDialogWin[0]
                22 -> LevelData.listtextDialogWin[1]
                23 -> LevelData.listtextDialogWin[2]
                24 -> LevelData.listtextDialogWin[3]
                25 -> LevelData.listtextDialogWin[4]
                26 -> LevelData.listtextDialogWin[0]
                27 -> LevelData.listtextDialogWin[1]
                28 -> LevelData.listtextDialogWin[2]
                29 -> LevelData.listtextDialogWin[3]
                30 -> LevelData.listtextDialogWin[4]
                31 -> LevelData.listtextDialogWin[0]
                32 -> LevelData.listtextDialogWin[1]
                33 -> LevelData.listtextDialogWin[2]
                34 -> LevelData.listtextDialogWin[3]
                35 -> LevelData.listtextDialogWin[4]
                else -> R.string.eror
            }

            return RoundInfoMulti(textRoundMulti = resultTextRoundMUlit, backgroundRound = resultBackgroundLvl, textCouplet  = resultcouplet,
                nameBtnone = resultbtnone, nameBtntwo = resultbtntwo, nameBtnthree = resultbtnthree, nameBtnfour = resultbtnfour,
                textDialogLose = resultTextDialogLose, textDialogWin = resultTextDialogWin ,music1 = resulmusic1, music2 = resulmusic2)
        }

}