package z.nova.rifmobolgame.model.round

import z.nova.rifmobolgame.R
import z.nova.rifmobolgame.model.round.LevelData.listBackground
import z.nova.rifmobolgame.model.round.LevelData.listTextLevl
import z.nova.rifmobolgame.model.round.LevelData.listbtnfour
import z.nova.rifmobolgame.model.round.LevelData.listbtnone
import z.nova.rifmobolgame.model.round.LevelData.listbtnthree
import z.nova.rifmobolgame.model.round.LevelData.listbtntwo
import z.nova.rifmobolgame.model.round.LevelData.listcouplet
import z.nova.rifmobolgame.model.round.LevelData.listmusic1
import z.nova.rifmobolgame.model.round.LevelData.listmusic2

class RoundInfoImpl(id: Int): RoundRepo {

    val idLvl = id

    override fun getRoundInf(): RoundInfo {

        val resultTextLvl = when(idLvl){
            1 -> listTextLevl[0]
            2 -> listTextLevl[1]
            3 -> listTextLevl[2]
            4 -> listTextLevl[3]
            5 -> listTextLevl[4]
            6 -> listTextLevl[5]
            7 -> listTextLevl[6]
            8 -> listTextLevl[7]
            9 -> listTextLevl[8]
            10 -> listTextLevl[9]
            11 -> listTextLevl[10]
            12 -> listTextLevl[11]
            13 -> listTextLevl[12]
            14 -> listTextLevl[13]
            15 -> listTextLevl[14]
            16 -> listTextLevl[15]
            17 -> listTextLevl[16]
            18 -> listTextLevl[17]
            19 -> listTextLevl[18]
            20 -> listTextLevl[19]
            21 -> listTextLevl[20]
            22 -> listTextLevl[21]
            23 -> listTextLevl[22]
            24 -> listTextLevl[23]
            25 -> listTextLevl[24]
            26 -> listTextLevl[25]
            27 -> listTextLevl[26]
            28 -> listTextLevl[27]
            29 -> listTextLevl[28]
            30 -> listTextLevl[29]
            31 -> listTextLevl[30]
            32 -> listTextLevl[31]
            33 -> listTextLevl[32]
            34 -> listTextLevl[33]
            35 -> listTextLevl[34]
            else -> R.string.eror
        }

        val resultBackgroundLvl = when(idLvl){
            1 -> listBackground[0]
            2 -> listBackground[1]
            3 -> listBackground[2]
            4 -> listBackground[3]
            5 -> listBackground[4]
            6 -> listBackground[5]
            7 -> listBackground[6]
            8 -> listBackground[7]
            9 -> listBackground[8]
            10 -> listBackground[9]
            11 -> listBackground[0]
            12 -> listBackground[1]
            13 -> listBackground[2]
            14 -> listBackground[3]
            15 -> listBackground[4]
            16 -> listBackground[5]
            17 -> listBackground[6]
            18 -> listBackground[7]
            19 -> listBackground[8]
            20 -> listBackground[9]
            21 -> listBackground[0]
            22 -> listBackground[1]
            23 -> listBackground[2]
            24 -> listBackground[3]
            25 -> listBackground[4]
            26 -> listBackground[5]
            27 -> listBackground[6]
            28 -> listBackground[7]
            29 -> listBackground[8]
            30 -> listBackground[9]
            31 -> listBackground[0]
            32 -> listBackground[1]
            33 -> listBackground[2]
            34 -> listBackground[3]
            35 -> listBackground[4]
            else -> listBackground[0]
        }

        val resultcouplet = when(idLvl){
            1 -> listcouplet [0]
            2 -> listcouplet[1]
            3 -> listcouplet[2]
            4 -> listcouplet[3]
            5 -> listcouplet[4]
            6 -> listcouplet[5]
            7 -> listcouplet[6]
            8 -> listcouplet[7]
            9 -> listcouplet[8]
            10 -> listcouplet[9]
            11 -> listcouplet[10]
            12 -> listcouplet[11]
            13 -> listcouplet[12]
            14 -> listcouplet[13]
            15 -> listcouplet[14]
            16 -> listcouplet[15]
            17 -> listcouplet[16]
            18 -> listcouplet[17]
            19 -> listcouplet[18]
            20 -> listcouplet[19]
            21 -> listcouplet[20]
            22 -> listcouplet[21]
            23 -> listcouplet[22]
            24 -> listcouplet[23]
            25 -> listcouplet[24]
            26 -> listcouplet[25]
            27 -> listcouplet[26]
            28 -> listcouplet[27]
            29 -> listcouplet[28]
            30 -> listcouplet[29]
            31 -> listcouplet[30]
            32 -> listcouplet[31]
            33 -> listcouplet[32]
            34 -> listcouplet[33]
            35 -> listcouplet[34]
            else -> R.string.eror
        }

        val resultbtnone = when(idLvl){
            1 -> listbtnone[0]
            2 -> listbtnone[1]
            3 -> listbtnone[2]
            4 -> listbtnone[3]
            5 -> listbtnone[4]
            6 -> listbtnone[5]
            7 -> listbtnone[6]
            8 -> listbtnone[7]
            9 -> listbtnone[8]
            10 -> listbtnone[9]
            11 -> listbtnone[10]
            12 -> listbtnone[11]
            13 -> listbtnone[12]
            14 -> listbtnone[13]
            15 -> listbtnone[14]
            16 -> listbtnone[15]
            17 -> listbtnone[16]
            18 -> listbtnone[17]
            19 -> listbtnone[18]
            20 -> listbtnone[19]
            21 -> listbtnone[20]
            22 -> listbtnone[21]
            23 -> listbtnone[22]
            24 -> listbtnone[23]
            25 -> listbtnone[24]
            26 -> listbtnone[25]
            27 -> listbtnone[26]
            28 -> listbtnone[27]
            29 -> listbtnone[28]
            30 -> listbtnone[29]
            31 -> listbtnone[30]
            32 -> listbtnone[31]
            33 -> listbtnone[32]
            34 -> listbtnone[33]
            35 -> listbtnone[34]
            else -> R.string.eror
        }

        val resultbtntwo = when(idLvl){
            1 -> listbtntwo[0]
            2 -> listbtntwo[1]
            3 -> listbtntwo[2]
            4 -> listbtntwo[3]
            5 -> listbtntwo[4]
            6 -> listbtntwo[5]
            7 -> listbtntwo[6]
            8 -> listbtntwo[7]
            9 -> listbtntwo[8]
            10 -> listbtntwo[9]
            11 -> listbtntwo[10]
            12 -> listbtntwo[11]
            13 -> listbtntwo[12]
            14 -> listbtntwo[13]
            15 -> listbtntwo[14]
            16 -> listbtntwo[15]
            17 -> listbtntwo[16]
            18 -> listbtntwo[17]
            19 -> listbtntwo[18]
            20 -> listbtntwo[19]
            21 -> listbtntwo[20]
            22 -> listbtntwo[21]
            23 -> listbtntwo[22]
            24 -> listbtntwo[23]
            25 -> listbtntwo[24]
            26 -> listbtntwo[25]
            27 -> listbtntwo[26]
            28 -> listbtntwo[27]
            29 -> listbtntwo[28]
            30 -> listbtntwo[29]
            31 -> listbtntwo[30]
            32 -> listbtntwo[31]
            33 -> listbtntwo[32]
            34 -> listbtntwo[33]
            35 -> listbtntwo[34]
            else -> R.string.eror
        }

        val resultbtnthree = when(idLvl){
            1 -> listbtnthree[0]
            2 -> listbtnthree[1]
            3 -> listbtnthree[2]
            4 -> listbtnthree[3]
            5 -> listbtnthree[4]
            6 -> listbtnthree[5]
            7 -> listbtnthree[6]
            8 -> listbtnthree[7]
            9 -> listbtnthree[8]
            10 -> listbtnthree[9]
            11 -> listbtnthree[10]
            12 -> listbtnthree[11]
            13 -> listbtnthree[12]
            14 -> listbtnthree[13]
            15 -> listbtnthree[14]
            16 -> listbtnthree[15]
            17 -> listbtnthree[16]
            18 -> listbtnthree[17]
            19 -> listbtnthree[18]
            20 -> listbtnthree[19]
            21 -> listbtnthree[20]
            22 -> listbtnthree[21]
            23 -> listbtnthree[22]
            24 -> listbtnthree[23]
            25 -> listbtnthree[24]
            26 -> listbtnthree[25]
            27 -> listbtnthree[26]
            28 -> listbtnthree[27]
            29 -> listbtnthree[28]
            30 -> listbtnthree[29]
            31 -> listbtnthree[30]
            32 -> listbtnthree[31]
            33 -> listbtnthree[32]
            34 -> listbtnthree[33]
            35 -> listbtnthree[34]
            else -> R.string.eror
        }

        val resultbtnfour = when(idLvl){
            1 -> listbtnfour[0]
            2 -> listbtnfour[1]
            3 -> listbtnfour[2]
            4 -> listbtnfour[3]
            5 -> listbtnfour[4]
            6 -> listbtnfour[5]
            7 -> listbtnfour[6]
            8 -> listbtnfour[7]
            9 -> listbtnfour[8]
            10 -> listbtnfour[9]
            11 -> listbtnfour[10]
            12 -> listbtnfour[11]
            13 -> listbtnfour[12]
            14 -> listbtnfour[13]
            15 -> listbtnfour[14]
            16 -> listbtnfour[15]
            17 -> listbtnfour[16]
            18 -> listbtnfour[17]
            19 -> listbtnfour[18]
            20 -> listbtnfour[19]
            21 -> listbtnfour[20]
            22 -> listbtnfour[21]
            23 -> listbtnfour[22]
            24 -> listbtnfour[23]
            25 -> listbtnfour[24]
            26 -> listbtnfour[25]
            27 -> listbtnfour[26]
            28 -> listbtnfour[27]
            29 -> listbtnfour[28]
            30 -> listbtnfour[29]
            31 -> listbtnfour[30]
            32 -> listbtnfour[31]
            33 -> listbtnfour[32]
            34 -> listbtnfour[33]
            35 -> listbtnfour[34]
            else -> R.string.eror
        }

        val resulmusic1 = when(idLvl){
            1 -> listmusic1[0]
            2 -> listmusic1[1]
            3 -> listmusic1[2]
            4 -> listmusic1[3]
            5 -> listmusic1[4]
            6 -> listmusic1[5]
            7 -> listmusic1[6]
            8 -> listmusic1[7]
            9 -> listmusic1[8]
            10 -> listmusic1[9]
            11 -> listmusic1[10]
            12 -> listmusic1[11]
            13 -> listmusic1[12]
            14 -> listmusic1[13]
            15 -> listmusic1[14]
            16 -> listmusic1[15]
            17 -> listmusic1[16]
            18 -> listmusic1[17]
            19 -> listmusic1[18]
            20 -> listmusic1[19]
            21 -> listmusic1[20]
            22 -> listmusic1[21]
            23 -> listmusic1[22]
            24 -> listmusic1[23]
            25 -> listmusic1[24]
            26 -> listmusic1[25]
            27 -> listmusic1[26]
            28 -> listmusic1[27]
            29 -> listmusic1[28]
            30 -> listmusic1[29]
            31 -> listmusic1[30]
            32 -> listmusic1[31]
            33 -> listmusic1[32]
            34 -> listmusic1[33]
            35 -> listmusic1[34]
            else -> R.raw.eggs1
        }

        val resulmusic2 = when(idLvl){
            1 -> listmusic2[0]
            2 -> listmusic2[1]
            3 -> listmusic2[2]
            4 -> listmusic2[3]
            5 -> listmusic2[4]
            6 -> listmusic2[5]
            7 -> listmusic2[6]
            8 -> listmusic2[7]
            9 -> listmusic2[8]
            10 -> listmusic2[9]
            11 -> listmusic2[10]
            12 -> listmusic2[11]
            13 -> listmusic2[12]
            14 -> listmusic2[13]
            15 -> listmusic2[14]
            16 -> listmusic2[15]
            17 -> listmusic2[16]
            18 -> listmusic2[17]
            19 -> listmusic2[18]
            20 -> listmusic2[19]
            21 -> listmusic2[20]
            22 -> listmusic2[21]
            23 -> listmusic2[22]
            24 -> listmusic2[23]
            25 -> listmusic2[24]
            26 -> listmusic2[25]
            27 -> listmusic2[26]
            28 -> listmusic2[27]
            29 -> listmusic2[28]
            30 -> listmusic2[29]
            31 -> listmusic2[30]
            32 -> listmusic2[31]
            33 -> listmusic2[32]
            34 -> listmusic2[33]
            35 -> listmusic2[34]
            else -> R.raw.eggs2
        }



        return RoundInfo(textLvl = resultTextLvl, backgroundRound = resultBackgroundLvl,
            nameBtnone = resultbtnone, nameBtntwo = resultbtntwo, textCouplet  = resultcouplet ,nameBtnthree = resultbtnthree, nameBtnfour = resultbtnfour,
       music1 = resulmusic1, music2 = resulmusic2)

    }
}